-- ============================================================
-- SEED SCRIPT - Datos de ejemplo para plataforma profesional
-- Limpia datos viejos e inserta 8 cursos completos con modulos y lecciones
-- ============================================================
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- Limpiar datos de prueba anteriores
DELETE FROM lesson_progress;
DELETE FROM lessons;
DELETE FROM modules;
DELETE FROM enrollments;
DELETE FROM certificates;
DELETE FROM reviews;
DELETE FROM notifications;
DELETE FROM courses;
ALTER TABLE courses AUTO_INCREMENT = 1;
ALTER TABLE modules AUTO_INCREMENT = 1;
ALTER TABLE lessons AUTO_INCREMENT = 1;

-- ============================================================
-- CURSOS PROFESIONALES
-- ============================================================
INSERT INTO `courses` (`slug`,`title`,`short_description`,`description`,`level`,`duration_hours`,`thumbnail`,`banner`,`requirements`,`objectives`,`category`,`tags`,`status`,`total_lessons`) VALUES
('inteligencia-artificial','Inteligencia Artificial: De Cero a Experto','Domina los fundamentos de la IA, desde logica computacional hasta redes neuronales.','Este curso te llevara desde los conceptos basicos de la logica computacional hasta la implementacion de redes neuronales capaces de aprender por si solas. Aprenderas los principios matematicos detras del Machine Learning, como funcionan los algoritmos de clasificacion y como entrenar modelos con datos reales. Al final del curso seras capaz de construir tu propio perceptron y entender la arquitectura de una red neuronal profunda.','Intermedio',40,'assets/images/courses/ia-thumb.jpg','assets/images/courses/ia-banner.jpg','Conocimientos basicos de matematicas y logica.|Python basico (recomendado).','Comprender que es la IA y sus aplicaciones reales.|Implementar un Perceptron desde cero.|Entrenar redes neuronales simples.|Aplicar algoritmos de clasificacion.|Evaluar modelos de ML.','Inteligencia Artificial','IA, Machine Learning, Redes Neuronales, Python','active',12),

('machine-learning','Machine Learning Practico con Python','Aprende los algoritmos esenciales de ML y aplicalos en proyectos reales.','Sumergete en el mundo del Machine Learning con un enfoque completamente practico. Aprenderas regresion, clasificacion, clustering y mucho mas, usando Python y las librerias mas demandadas por la industria como scikit-learn, pandas y matplotlib. Cada modulo incluye un proyecto real que podras agregar a tu portafolio profesional.','Avanzado',50,'assets/images/courses/ml-thumb.jpg','assets/images/courses/ml-banner.jpg','Python intermedio.|Estadistica basica.|Algebra lineal basica.','Implementar algoritmos supervisados y no supervisados.|Preprocesar datos correctamente.|Evaluar y optimizar modelos.|Desplegar modelos en produccion.|Construir un portafolio de proyectos ML.','Inteligencia Artificial','ML, Python, scikit-learn, Data Science','active',12),

('python-desde-cero','Python desde Cero: La Guia Completa','Aprende a programar en Python desde absoluto cero hasta nivel intermedio-avanzado.','Python es el lenguaje de programacion mas demandado del mundo. En este curso aprenderas todo lo que necesitas saber para convertirte en un programador Python competente. Cubrimos desde la instalacion del entorno, variables y estructuras de datos, hasta programacion orientada a objetos, manejo de archivos, APIs y mucho mas. Perfecto para principiantes sin experiencia previa en programacion.','Basico',35,'assets/images/courses/python-thumb.jpg','assets/images/courses/python-banner.jpg','No se requiere experiencia previa en programacion.','Instalar y configurar Python correctamente.|Manejar variables, listas, diccionarios y funciones.|Programar orientado a objetos en Python.|Leer y escribir archivos.|Consumir APIs REST.|Crear scripts de automatizacion.','Programacion','Python, Programacion, Backend, Scripting','active',15),

('sql-bases-de-datos','SQL y Bases de Datos Relacionales','Domina SQL desde lo basico hasta consultas avanzadas y diseno de bases de datos.','Las bases de datos son el corazon de cualquier aplicacion moderna. En este curso aprenderas SQL desde cero: como crear tablas, insertar datos, hacer consultas complejas con JOINs, subconsultas, indices y procedimientos almacenados. Tambien aprenderas a disenar esquemas de bases de datos eficientes usando normalizacion y buenas practicas de la industria.','Basico',25,'assets/images/courses/sql-thumb.jpg','assets/images/courses/sql-banner.jpg','No se requiere experiencia previa.|Logica basica de computacion.','Crear y gestionar bases de datos MySQL/PostgreSQL.|Escribir consultas SELECT, INSERT, UPDATE, DELETE.|Usar JOINs para combinar tablas.|Disenar esquemas normalizados.|Optimizar consultas con indices.|Usar transacciones y procedimientos almacenados.','Bases de Datos','SQL, MySQL, PostgreSQL, Bases de Datos','active',10),

('desarrollo-web-full-stack','Desarrollo Web Full Stack Moderno','Construye aplicaciones web completas con HTML, CSS, JavaScript, PHP y MySQL.','El desarrollo web Full Stack te permite crear aplicaciones completas de principio a fin. En este curso aprenderas todo el stack tecnologico moderno: desde estructurar paginas con HTML5 y estilizarlas con CSS3, hasta crear interactividad con JavaScript, construir APIs con PHP y persistir datos con MySQL. Terminaras el curso con dos proyectos reales completos en tu portafolio.','Intermedio',60,'assets/images/courses/web-thumb.jpg','assets/images/courses/web-banner.jpg','Conocimientos basicos de computacion.|Python o cualquier lenguaje de programacion (recomendado).','Crear estructuras HTML5 semanticas.|Disenar interfaces responsivas con CSS3.|Programar interactividad con JavaScript ES6+.|Construir APIs RESTful con PHP.|Gestionar bases de datos MySQL.|Desplegar aplicaciones en servidor.','Desarrollo Web','HTML, CSS, JavaScript, PHP, MySQL, Full Stack','active',15),

('algoritmos-geneticos','Algoritmos Geneticos y Computacion Evolutiva','Aprende a resolver problemas complejos de optimizacion con algoritmos inspirados en la biologia.','La computacion evolutiva es una de las areas mas fascinantes de la inteligencia artificial. Los algoritmos geneticos imitan el proceso de seleccion natural para encontrar soluciones optimas a problemas que serian imposibles de resolver con metodos tradicionales. En este curso aprenderas los fundamentos matematicos y programaras tus propios algoritmos geneticos desde cero.','Avanzado',30,'assets/images/courses/genetic-thumb.jpg','assets/images/courses/genetic-banner.jpg','Programacion intermedia (Python recomendado).|Matematicas basicas.|Estadistica elemental.','Entender los principios de la seleccion natural aplicados a la computacion.|Implementar operadores geneticos: seleccion, cruce y mutacion.|Definir funciones de aptitud correctamente.|Aplicar AG a problemas de optimizacion reales.','Inteligencia Artificial','Algoritmos Geneticos, IA, Optimizacion, Computacion Evolutiva','active',10),

('data-science','Data Science: Analisis y Visualizacion de Datos','Transforma datos en insights accionables con Python, pandas y visualizaciones profesionales.','Los datos son el nuevo petroleo. En este curso aprenderas el flujo completo del Data Science: desde la recoleccion y limpieza de datos hasta el analisis exploratorio y la visualizacion de insights que generen valor para las organizaciones. Usaras las herramientas estandar de la industria: Python, pandas, NumPy, matplotlib, seaborn y Jupyter Notebooks.','Intermedio',45,'assets/images/courses/ds-thumb.jpg','assets/images/courses/ds-banner.jpg','Python basico.|Estadistica descriptiva.|Excel o Google Sheets (recomendado).','Recolectar y limpiar datasets reales.|Realizar analisis exploratorio de datos (EDA).|Crear visualizaciones profesionales e interactivas.|Identificar patrones y tendencias en datos.|Comunicar hallazgos efectivamente.','Ciencia de Datos','Data Science, Python, pandas, visualizacion, EDA','active',12),

('javascript-moderno','JavaScript Moderno: ES6+ y mas alla','Domina JavaScript moderno desde los fundamentos hasta async/await y primeros pasos con React.','JavaScript es el lenguaje del web. En este curso aprenderas JavaScript desde sus fundamentos hasta las caracteristicas modernas de ES6+: arrow functions, destructuring, Promises, async/await, modulos y mucho mas. Luego de dominar el lenguaje, daras tus primeros pasos con React para el frontend, convirtiendote en un desarrollador JavaScript moderno y demandado.','Intermedio',55,'assets/images/courses/js-thumb.jpg','assets/images/courses/js-banner.jpg','HTML y CSS basico.|Logica de programacion elemental.','Dominar JavaScript ES6+ completamente.|Trabajar con arrays, objetos y funciones de orden superior.|Manejar asincronismo con Promises y async/await.|Crear componentes con React.|Gestionar el estado de aplicaciones.|Construir proyectos reales para el portafolio.','Desarrollo Web','JavaScript, ES6, React, Frontend','active',14);

-- ============================================================
-- MODULOS POR CURSO
-- ============================================================

-- Curso: inteligencia-artificial (id=1)
INSERT INTO `modules` (`course_id`,`title`,`description`,`sort_order`) VALUES
(1,'Fundamentos de la IA','Historia, conceptos basicos y aplicaciones de la Inteligencia Artificial en el mundo real',1),
(1,'Logica y Representacion del Conocimiento','Como las maquinas razonan y representan informacion del mundo',2),
(1,'El Perceptron: Primera Red Neuronal','Teoria matematica y practica del perceptron de Rosenblatt',3),
(1,'Redes Neuronales y Deep Learning','Arquitecturas modernas y entrenamiento de redes neuronales profundas',4);

-- Curso: machine-learning (id=2)
INSERT INTO `modules` (`course_id`,`title`,`description`,`sort_order`) VALUES
(2,'Introduccion al Machine Learning','Tipos de aprendizaje, ecosistema de herramientas y flujo de trabajo en ML',1),
(2,'Aprendizaje Supervisado','Regresion, clasificacion, evaluacion y validacion cruzada de modelos',2),
(2,'Aprendizaje No Supervisado','Clustering, reduccion de dimensionalidad y deteccion de anomalias',3),
(2,'Proyectos Reales de ML','Aplicar Machine Learning a problemas reales con datasets publicos',4);

-- Curso: python-desde-cero (id=3)
INSERT INTO `modules` (`course_id`,`title`,`description`,`sort_order`) VALUES
(3,'Primeros Pasos con Python','Instalacion, entorno de desarrollo y primeros programas',1),
(3,'Estructuras de Datos','Listas, diccionarios, tuplas y conjuntos en profundidad',2),
(3,'Control de Flujo y Funciones','Condicionales, bucles, funciones propias y recursion',3),
(3,'Programacion Orientada a Objetos','Clases, herencia, encapsulamiento y polimorfismo en Python',4),
(3,'Python Avanzado y APIs','Decoradores, generadores, context managers y consumo de APIs REST',5);

-- Curso: sql-bases-de-datos (id=4)
INSERT INTO `modules` (`course_id`,`title`,`description`,`sort_order`) VALUES
(4,'Fundamentos de Bases de Datos','Modelo relacional, entidades, atributos y relaciones',1),
(4,'SQL Basico: CRUD Completo','SELECT, INSERT, UPDATE, DELETE y clausulas fundamentales',2),
(4,'SQL Avanzado: JOINs y Subconsultas','Combinacion de tablas, consultas anidadas y vistas',3),
(4,'Optimizacion y Buenas Practicas','Indices, transacciones, normalizacion y procedimientos almacenados',4);

-- Curso: desarrollo-web-full-stack (id=5)
INSERT INTO `modules` (`course_id`,`title`,`description`,`sort_order`) VALUES
(5,'HTML5 y CSS3 Moderno','Semantica HTML5, Flexbox, CSS Grid y animaciones CSS',1),
(5,'JavaScript para el Frontend','Manipulacion del DOM, eventos, fetch y almacenamiento local',2),
(5,'PHP y Programacion del Servidor','PHP 8, programacion orientada a objetos y arquitectura MVC',3),
(5,'MySQL y Bases de Datos en PHP','PDO, consultas preparadas, relaciones y migraciones',4),
(5,'Proyecto Final: App Completa','Construir una aplicacion web real de principio a fin con despliegue',5);

-- Curso: algoritmos-geneticos (id=6)
INSERT INTO `modules` (`course_id`,`title`,`description`,`sort_order`) VALUES
(6,'Introduccion a la Computacion Evolutiva','Principios biologicos aplicados a la computacion y optimizacion',1),
(6,'Estructura de un Algoritmo Genetico','Poblacion, cromosomas, genes, codificacion y funcion de aptitud',2),
(6,'Operadores Geneticos en Detalle','Seleccion por torneo, cruce de un punto y mutacion adaptativa',3),
(6,'Aplicaciones y Proyectos Finales','Resolver problemas de optimizacion reales: TSP, knapsack y scheduling',4);

-- Curso: data-science (id=7)
INSERT INTO `modules` (`course_id`,`title`,`description`,`sort_order`) VALUES
(7,'El Rol del Data Scientist','Flujo de trabajo CRISP-DM, herramientas y mercado laboral en 2024',1),
(7,'Recoleccion y Limpieza de Datos','Web scraping, APIs publicas y preprocesamiento con pandas',2),
(7,'Analisis Exploratorio (EDA)','Estadisticas descriptivas, distribuciones y correlaciones',3),
(7,'Visualizacion Avanzada de Datos','matplotlib, seaborn, plotly y dashboards interactivos',4);

-- Curso: javascript-moderno (id=8)
INSERT INTO `modules` (`course_id`,`title`,`description`,`sort_order`) VALUES
(8,'JavaScript Fundamentals','Tipos de datos, variables, operadores, funciones y scope',1),
(8,'JavaScript ES6+ Moderno','Arrow functions, destructuring, spread, modules y clases',2),
(8,'Asincronismo en JavaScript','Event loop, callbacks, Promises, async/await y Fetch API',3),
(8,'Introduccion a React','Componentes, JSX, props, state, useState y useEffect',4),
(8,'Proyecto: App React Completa','Construir una SPA con React, estado global y consumo de APIs',5);

-- ============================================================
-- LECCIONES POR MODULO (3 lecciones por modulo)
-- Module IDs: 1-4=IA, 5-8=ML, 9-13=Python, 14-17=SQL, 18-22=Web, 23-26=Genetic, 27-30=DS, 31-35=JS
-- ============================================================

-- MODULO 1: Fundamentos de IA (module_id=1)
INSERT INTO `lessons` (`module_id`,`title`,`content`,`video_url`,`video_type`,`duration_minutes`,`sort_order`,`is_free`) VALUES
(1,'Que es la Inteligencia Artificial','<h2>Introduccion a la IA</h2><p>La Inteligencia Artificial (IA) es la capacidad de las maquinas para imitar procesos cognitivos humanos como el aprendizaje, el razonamiento, la resolucion de problemas, la percepcion y la comprension del lenguaje.</p><h3>Tipos de IA</h3><ul><li><strong>IA Estrecha (ANI):</strong> Diseñada para una tarea especifica (ej: reconocimiento facial, recomendaciones de Netflix).</li><li><strong>IA General (AGI):</strong> Capaz de realizar cualquier tarea intelectual humana.</li><li><strong>Superinteligencia (ASI):</strong> Forma hipotetica que supera la inteligencia humana en todos los aspectos.</li></ul><h3>Por que estudiar IA?</h3><p>La IA es la tecnologia mas transformadora del siglo XXI. Dominarla abre puertas a oportunidades laborales extraordinarias y a la capacidad de construir soluciones que impactan millones de vidas.</p>','https://www.youtube.com/embed/mJeNghZXtMo','youtube',15,1,1),
(1,'Historia y Evolucion de la IA','<h2>Historia de la Inteligencia Artificial</h2><p>La IA tiene sus raices en los trabajos de matematicos y logicos del siglo XX. El termino fue acunado oficialmente en 1956 por John McCarthy en la Conferencia de Dartmouth.</p><h3>Cronologia Clave</h3><ul><li><strong>1950:</strong> Test de Turing - Alan Turing propone una prueba de inteligencia maquina.</li><li><strong>1956:</strong> Conferencia de Dartmouth - nace la IA como disciplina academica.</li><li><strong>1980s:</strong> Sistemas expertos - la primera oleada de IA comercial.</li><li><strong>1997:</strong> Deep Blue vence al campeon mundial de ajedrez Garry Kasparov.</li><li><strong>2012:</strong> AlexNet revoluciona el reconocimiento de imagenes con Deep Learning.</li><li><strong>2016:</strong> AlphaGo vence al campeon mundial de Go.</li><li><strong>2022:</strong> ChatGPT democratiza el acceso a la IA generativa.</li></ul>','','none',20,2,0),
(1,'Aplicaciones Reales de la IA','<h2>IA en el Mundo Real</h2><p>La Inteligencia Artificial esta presente en nuestra vida cotidiana de formas sorprendentes:</p><h3>Casos de Uso Actuales</h3><ul><li><strong>Salud:</strong> Diagnostico de cancer, prediccion de enfermedades, descubrimiento de farmacos.</li><li><strong>Finanzas:</strong> Deteccion de fraudes en tiempo real, trading algoritmico.</li><li><strong>Entretenimiento:</strong> Recomendaciones personalizadas en Netflix, Spotify, YouTube.</li><li><strong>Transporte:</strong> Vehiculos autonomos, optimizacion de rutas (Google Maps).</li><li><strong>Asistentes:</strong> Siri, Alexa, Google Assistant, ChatGPT.</li><li><strong>Vision:</strong> Reconocimiento facial, filtros de redes sociales, inspeccion industrial.</li></ul>','','none',18,3,0);

-- MODULO 2: Logica y Conocimiento (module_id=2)
INSERT INTO `lessons` (`module_id`,`title`,`content`,`video_url`,`video_type`,`duration_minutes`,`sort_order`,`is_free`) VALUES
(2,'Representacion del Conocimiento','<h2>Como las Maquinas Representan el Conocimiento</h2><p>Para que una IA pueda razonar, necesita representar el conocimiento del mundo en un formato que las computadoras puedan procesar.</p><h3>Metodos de Representacion</h3><ul><li><strong>Logica Proposicional:</strong> Declaraciones verdaderas o falsas.</li><li><strong>Logica de Primer Orden:</strong> Predicados, cuantificadores y funciones.</li><li><strong>Redes Semanticas:</strong> Grafos de conceptos relacionados.</li><li><strong>Marcos (Frames):</strong> Estructuras para representar objetos y sus propiedades.</li><li><strong>Ontologias:</strong> Vocabularios formales de un dominio.</li></ul>','','none',22,1,0),
(2,'Busqueda y Solucion de Problemas','<h2>Algoritmos de Busqueda en IA</h2><p>Muchos problemas de IA se pueden reformular como una busqueda en un espacio de estados. Los algoritmos de busqueda son fundamentales en IA clasica.</p><h3>Tipos de Busqueda</h3><ul><li><strong>BFS (Busqueda en Anchura):</strong> Explora todos los nodos de un nivel antes de pasar al siguiente.</li><li><strong>DFS (Busqueda en Profundidad):</strong> Explora una rama completamente antes de retroceder.</li><li><strong>A*:</strong> Usa heuristica para encontrar el camino optimo eficientemente.</li><li><strong>Minimax:</strong> Para juegos de dos jugadores como ajedrez.</li></ul>','https://www.youtube.com/embed/oDqjPvD1T-0','youtube',25,2,0),
(2,'Razonamiento con Incertidumbre','<h2>La Probabilidad en la IA</h2><p>El mundo real es incierto. Las IA modernas usan probabilidad para razonar con informacion incompleta o ruidosa.</p><h3>Conceptos Clave</h3><ul><li><strong>Redes Bayesianas:</strong> Representan dependencias probabilisticas entre variables.</li><li><strong>Teorema de Bayes:</strong> Actualizar creencias en base a evidencia nueva.</li><li><strong>Modelos de Markov:</strong> Procesos probabilisticos con estados ocultos.</li></ul>','','none',20,3,0);

-- MODULO 3: El Perceptron (module_id=3)
INSERT INTO `lessons` (`module_id`,`title`,`content`,`video_url`,`video_type`,`duration_minutes`,`sort_order`,`is_free`) VALUES
(3,'Inspiracion Biologica: La Neurona','<h2>De la Neurona Biologica al Perceptron</h2><p>El perceptron fue diseñado como una simplificacion matematica de la neurona biologica. Comprender la neurona biologica nos ayuda a entender por que el perceptron funciona como lo hace.</p><h3>La Neurona Biologica</h3><p>Una neurona recibe señales electricas a traves de sus <strong>dendritas</strong>, las procesa en el <strong>soma</strong> (cuerpo celular), y si la señal supera un umbral, envia un impulso por el <strong>axon</strong>. Esta es exactamente la logica que imita el perceptron.</p>','','none',18,1,0),
(3,'Matematica del Perceptron','<h2>El Perceptron de Rosenblatt</h2><p>Un perceptron toma multiples entradas, las pondera y produce una salida binaria. La formula es:</p><pre><code>salida = 1 si (w1*x1 + w2*x2 + ... + wn*xn + bias) >= 0\n         0 en caso contrario</code></pre><h3>Componentes</h3><ul><li><strong>Entradas (x):</strong> Los datos que el perceptron recibe.</li><li><strong>Pesos (w):</strong> La importancia de cada entrada.</li><li><strong>Bias:</strong> Permite desplazar la funcion de activacion.</li><li><strong>Funcion de activacion:</strong> Determina cuando el perceptron se activa.</li></ul>','https://www.youtube.com/embed/aircAruvnKk','youtube',30,2,0),
(3,'Implementando un Perceptron en Python','<h2>Codigo: Tu Primer Perceptron</h2><p>Implementaremos un perceptron desde cero en Python para que entiendas cada parte del algoritmo:</p><pre><code>import numpy as np\n\nclass Perceptron:\n    def __init__(self, tasa_aprendizaje=0.01, n_iteraciones=1000):\n        self.tasa = tasa_aprendizaje\n        self.n_iter = n_iteraciones\n\n    def fit(self, X, y):\n        self.pesos = np.zeros(X.shape[1])\n        self.bias = 0\n\n        for _ in range(self.n_iter):\n            for xi, yi in zip(X, y):\n                prediccion = self.predict(xi)\n                error = yi - prediccion\n                self.pesos += self.tasa * error * xi\n                self.bias += self.tasa * error\n\n    def predict(self, X):\n        suma = np.dot(X, self.pesos) + self.bias\n        return np.where(suma >= 0, 1, 0)</code></pre>','','none',35,3,0);

-- MODULO 4: Redes Neuronales (module_id=4)
INSERT INTO `lessons` (`module_id`,`title`,`content`,`video_url`,`video_type`,`duration_minutes`,`sort_order`,`is_free`) VALUES
(4,'Arquitectura de una Red Neuronal','<h2>De Perceptron a Red Neuronal Profunda</h2><p>Una red neuronal es simplemente una coleccion de perceptrones organizados en capas. Cada capa transforma la representacion de los datos, extrayendo caracteristicas cada vez mas abstractas.</p><h3>Capas de una Red Neuronal</h3><ul><li><strong>Capa de Entrada:</strong> Recibe los datos en bruto.</li><li><strong>Capas Ocultas:</strong> Aprenden representaciones intermedias.</li><li><strong>Capa de Salida:</strong> Produce la prediccion final.</li></ul>','https://www.youtube.com/embed/aircAruvnKk','youtube',28,1,0),
(4,'Backpropagation: Como Aprenden las Redes','<h2>El Algoritmo de Retropropagacion</h2><p>Backpropagation es el algoritmo que permite entrenar redes neuronales calculando los gradientes del error con respecto a cada peso, y actualizando los pesos para minimizar el error.</p><p>El proceso es:</p><ol><li>Propagacion hacia adelante: calcular la prediccion.</li><li>Calcular el error (loss).</li><li>Propagacion hacia atras: calcular gradientes.</li><li>Actualizar pesos con descenso de gradiente.</li></ol>','','none',35,2,0),
(4,'Funciones de Activacion Modernas','<h2>Funciones de Activacion en Deep Learning</h2><p>La funcion de activacion determina si una neurona debe activarse o no. La eleccion correcta es crucial para el entrenamiento efectivo.</p><ul><li><strong>Sigmoid:</strong> Salida entre 0 y 1. Buena para clasificacion binaria.</li><li><strong>Tanh:</strong> Salida entre -1 y 1. Centrada en cero.</li><li><strong>ReLU:</strong> max(0, x). La mas popular en redes profundas.</li><li><strong>Softmax:</strong> Convierte logits en probabilidades para clasificacion multiclase.</li></ul>','','none',25,3,0);

-- MODULO 5: Intro ML (module_id=5)
INSERT INTO `lessons` (`module_id`,`title`,`content`,`video_url`,`video_type`,`duration_minutes`,`sort_order`,`is_free`) VALUES
(5,'Que es el Machine Learning','<h2>Machine Learning: El Arte de Aprender de Datos</h2><p>El Machine Learning es una rama de la IA que permite a los sistemas aprender y mejorar automaticamente a partir de la experiencia sin ser programados explicitamente.</p><h3>Los 3 Tipos de Aprendizaje</h3><ul><li><strong>Supervisado:</strong> Aprender de datos etiquetados (ejemplos con respuesta correcta).</li><li><strong>No Supervisado:</strong> Encontrar patrones en datos sin etiquetas.</li><li><strong>Por Refuerzo:</strong> Aprender por ensayo y error con un sistema de recompensas.</li></ul>','https://www.youtube.com/embed/f_uwKZIAeM0','youtube',20,1,1),
(5,'El Flujo de Trabajo en ML','<h2>Pipeline Estandar de Machine Learning</h2><p>Todo proyecto de ML sigue un proceso sistematico conocido como pipeline:</p><ol><li><strong>Definir el problema</strong> y los objetivos de negocio.</li><li><strong>Recopilar datos</strong> relevantes y suficientes.</li><li><strong>Explorar y limpiar</strong> los datos (EDA).</li><li><strong>Ingenieria de caracteristicas</strong> (feature engineering).</li><li><strong>Seleccionar y entrenar</strong> el modelo.</li><li><strong>Evaluar y mejorar</strong> el rendimiento.</li><li><strong>Desplegar</strong> el modelo en produccion.</li></ol>','','none',25,2,0),
(5,'Herramientas Esenciales de ML','<h2>El Ecosistema Python para ML</h2><ul><li><strong>NumPy:</strong> Computacion numerica eficiente con arrays multidimensionales.</li><li><strong>Pandas:</strong> Manipulacion y analisis de datos tabulares.</li><li><strong>Matplotlib/Seaborn:</strong> Visualizacion de datos.</li><li><strong>Scikit-learn:</strong> La libreria de ML mas completa y usada.</li><li><strong>TensorFlow/PyTorch:</strong> Para deep learning.</li><li><strong>Jupyter Notebook:</strong> Entorno interactivo para experimentacion.</li></ul>','','none',15,3,0);

-- Modulos 6-8 de ML
INSERT INTO `lessons` (`module_id`,`title`,`content`,`video_url`,`video_type`,`duration_minutes`,`sort_order`,`is_free`) VALUES
(6,'Regresion Lineal y Logistica','<h2>Los Algoritmos Base del ML Supervisado</h2><p>La regresion lineal predice valores continuos, mientras que la regresion logistica predice probabilidades (clasificacion). Son los algoritmos mas simples e interpretables del ML.</p>','','none',30,1,0),
(6,'Arboles de Decision y Random Forest','<h2>Modelos Basados en Arboles</h2><p>Los arboles de decision particionan el espacio de caracteristicas de forma recursiva. Random Forest combina multiples arboles para obtener predicciones mas robustas (ensemble learning).</p>','https://www.youtube.com/embed/J4Wdy0Wc_xQ','youtube',35,2,0),
(6,'Support Vector Machines (SVM)','<h2>Clasificacion con Margenes Maximos</h2><p>SVM encuentra el hiperplano que maximiza el margen entre clases. Es especialmente efectivo en espacios de alta dimensionalidad y problemas de clasificacion binaria.</p>','','none',28,3,0),
(7,'K-Means Clustering','<h2>Agrupamiento No Supervisado</h2><p>K-Means agrupa datos en K clusters minimizando la varianza intra-cluster. Es el algoritmo de clustering mas popular por su simplicidad y eficiencia.</p>','','none',25,1,0),
(7,'PCA: Reduccion de Dimensionalidad','<h2>Analisis de Componentes Principales</h2><p>PCA transforma los datos a un espacio de menor dimension preservando la maxima varianza posible. Es esencial para visualizar datos de alta dimensionalidad y reducir el costo computacional.</p>','https://www.youtube.com/embed/FgakZw6K1QQ','youtube',30,2,0),
(7,'Evaluacion y Validacion de Modelos','<h2>Metricas de Evaluacion en ML</h2><p>Elegir la metrica correcta es crucial. Accuracy, precision, recall, F1-score para clasificacion. MAE, MSE, R2 para regresion. Cross-validation para estimacion robusta del rendimiento.</p>','','none',25,3,0),
(8,'Proyecto: Clasificacion de Imagenes','<h2>Proyecto Real: Clasificador de Imagenes con CNN</h2><p>Construiremos un clasificador de imagenes usando una Red Neuronal Convolucional (CNN) con TensorFlow/Keras. El modelo aprendera a distinguir entre diferentes categorias de imagenes.</p>','https://www.youtube.com/embed/qFJeN9V1ZsI','youtube',45,1,0),
(8,'Proyecto: Sistema de Recomendacion','<h2>Proyecto: Motor de Recomendaciones</h2><p>Implementaremos un sistema de recomendacion basado en filtrado colaborativo, similar a los que usan Netflix y Spotify para sugerir contenido personalizado.</p>','','none',40,2,0),
(8,'Despliegue de Modelos ML en Produccion','<h2>De Jupyter Notebook a Produccion</h2><p>Aprenderemos a serializar modelos con joblib/pickle, crear APIs con Flask/FastAPI para exponer el modelo, y consideraciones de MLOps para mantener modelos en produccion.</p>','','none',35,3,0);

-- PYTHON MODULOS 9-13 (lecciones)
INSERT INTO `lessons` (`module_id`,`title`,`content`,`video_url`,`video_type`,`duration_minutes`,`sort_order`,`is_free`) VALUES
(9,'Instalacion de Python y VSCode','<h2>Configurando tu Entorno de Desarrollo</h2><p>Antes de escribir nuestro primer programa, necesitamos instalar Python y un editor de codigo.</p><ol><li>Ir a python.org y descargar la version mas reciente (3.11+).</li><li>Durante la instalacion, marcar "Add Python to PATH".</li><li>Descargar VSCode desde code.visualstudio.com.</li><li>Instalar la extension oficial de Python en VSCode.</li><li>Verificar: <code>python --version</code></li></ol>','https://www.youtube.com/embed/TqPzwenhMj0','youtube',12,1,1),
(9,'Variables y Tipos de Datos','<h2>Tu Primer Programa Python</h2><pre><code>print("Hola, Mundo!")\n\n# Variables\nnombre = "Python"\nversion = 3.11\nannio = 2024\nes_genial = True\n\nprint(f"Hola, {nombre} {version}!")</code></pre>','','none',20,2,1),
(9,'Entrada y Salida de Datos','<h2>Interactuando con el Usuario</h2><pre><code>nombre = input("Como te llamas? ")\nedad = int(input("Cuantos annios tienes? "))\nprint(f"Hola {nombre}! En 10 annios tendras {edad + 10} annios.")</code></pre>','','none',15,3,0),
(10,'Listas y Tuplas','<h2>Colecciones Ordenadas en Python</h2><p>Las listas son la estructura de datos mas versatil de Python. Son mutables, ordenadas y aceptan cualquier tipo de dato.</p><pre><code>frutas = ["manzana", "banana", "cereza"]\nfrutas.append("naranja")\nprint(frutas[0])  # manzana\nprint(frutas[-1]) # naranja</code></pre>','','none',25,1,0),
(10,'Diccionarios y Conjuntos','<h2>Colecciones con Clave-Valor</h2><p>Los diccionarios son fundamentales en Python. Almacenan pares clave-valor y permiten acceso en O(1).</p><pre><code>persona = {"nombre": "Ana", "edad": 25, "ciudad": "Bogota"}\nprint(persona["nombre"])  # Ana\npersona["profesion"] = "Ingeniera"</code></pre>','','none',28,2,0),
(10,'Comprensiones de Listas','<h2>Sintaxis Elegante y Pythonica</h2><p>Las comprensiones de lista permiten crear listas de forma concisa y readable.</p><pre><code>cuadrados = [x**2 for x in range(10)]\npares = [x for x in range(20) if x % 2 == 0]\nmatriz = [[i*j for j in range(5)] for i in range(5)]</code></pre>','','none',20,3,0),
(11,'Condicionales en Python','<h2>Toma de Decisiones con if/elif/else</h2><pre><code>nota = 85\nif nota >= 90:\n    print("Excelente")\nelif nota >= 75:\n    print("Bueno")\nelif nota >= 60:\n    print("Suficiente")\nelse:\n    print("Insuficiente")</code></pre>','','none',18,1,0),
(11,'Bucles: for y while','<h2>Repeticion en Python</h2><pre><code># Bucle for\nfor i in range(1, 6):\n    print(f"Iteracion {i}")\n\n# Bucle while\ncontador = 0\nwhile contador < 5:\n    print(f"Contador: {contador}")\n    contador += 1\n\n# Iterar sobre una lista\nfrutas = ["manzana", "banana", "pera"]\nfor fruta in frutas:\n    print(fruta.upper())</code></pre>','','none',22,2,0),
(11,'Funciones y Parametros','<h2>Reutilizacion de Codigo con Funciones</h2><pre><code>def saludar(nombre, saludo="Hola"):\n    """Saluda a una persona."""\n    return f"{saludo}, {nombre}!"\n\n# Funciones lambda\ndoblar = lambda x: x * 2\n\n# Funciones con *args y **kwargs\ndef suma(*args):\n    return sum(args)\n\nprint(suma(1, 2, 3, 4, 5))  # 15</code></pre>','','none',30,3,0),
(12,'Clases y Objetos','<h2>Programacion Orientada a Objetos en Python</h2><pre><code>class Animal:\n    def __init__(self, nombre, especie):\n        self.nombre = nombre\n        self.especie = especie\n\n    def presentarse(self):\n        return f"Soy {self.nombre}, un {self.especie}"\n\nperro = Animal("Rex", "perro")\nprint(perro.presentarse())</code></pre>','https://www.youtube.com/embed/pTB0EiLXUC8','youtube',35,1,0),
(12,'Herencia y Polimorfismo','<h2>Reutilizando y Extendiendo Clases</h2><pre><code>class Vehiculo:\n    def __init__(self, marca, velocidad_max):\n        self.marca = marca\n        self.velocidad_max = velocidad_max\n\n    def describir(self):\n        return f"{self.marca} - Max: {self.velocidad_max}km/h"\n\nclass Coche(Vehiculo):\n    def __init__(self, marca, velocidad_max, puertas):\n        super().__init__(marca, velocidad_max)\n        self.puertas = puertas</code></pre>','','none',30,2,0),
(12,'Manejo de Errores y Excepciones','<h2>Codigo Robusto con try/except</h2><pre><code>try:\n    numero = int(input("Ingresa un numero: "))\n    resultado = 100 / numero\n    print(f"Resultado: {resultado}")\nexcept ValueError:\n    print("Error: Debes ingresar un numero")\nexcept ZeroDivisionError:\n    print("Error: No se puede dividir por cero")\nfinally:\n    print("Operacion terminada")</code></pre>','','none',25,3,0),
(13,'Decoradores en Python','<h2>Funciones que Envuelven Funciones</h2><p>Los decoradores son una forma elegante de modificar o extender el comportamiento de funciones.</p><pre><code>import time\n\ndef medir_tiempo(func):\n    def wrapper(*args, **kwargs):\n        inicio = time.time()\n        resultado = func(*args, **kwargs)\n        fin = time.time()\n        print(f"{func.__name__} tardo {fin-inicio:.4f}s")\n        return resultado\n    return wrapper\n\n@medir_tiempo\ndef operacion_lenta():\n    time.sleep(1)</code></pre>','','none',30,1,0),
(13,'Generadores y Iteradores','<h2>Procesamiento Eficiente de Datos</h2><p>Los generadores producen valores uno a la vez, permitiendo trabajar con secuencias infinitas o datasets enormes sin cargar todo en memoria.</p><pre><code>def fibonacci():\n    a, b = 0, 1\n    while True:\n        yield a\n        a, b = b, a + b\n\ngen = fibonacci()\nfor _ in range(10):\n    print(next(gen))</code></pre>','','none',28,2,0),
(13,'Consumir APIs REST con Python','<h2>Conectando Python al Mundo</h2><p>Las APIs REST son la forma estandar de comunicacion entre servicios. Con Python y la libreria requests podemos consumir cualquier API facilmente.</p><pre><code>import requests\n\nurl = "https://api.github.com/users/python"\nresponse = requests.get(url)\n\nif response.status_code == 200:\n    data = response.json()\n    print(f"Repositorios: {data[\"public_repos\"]}")</code></pre>','','none',25,3,0);

-- SQL LECCIONES (modules 14-17)
INSERT INTO `lessons` (`module_id`,`title`,`content`,`video_url`,`video_type`,`duration_minutes`,`sort_order`,`is_free`) VALUES
(14,'Que es una Base de Datos Relacional','<h2>El Modelo Relacional</h2><p>Una base de datos relacional organiza los datos en tablas (relaciones) con filas y columnas. Las tablas se relacionan entre si mediante claves primarias y foraneas.</p>','https://www.youtube.com/embed/FR4QIeZaPeM','youtube',20,1,1),
(14,'Diseño de Esquemas y Normalizacion','<h2>Disenar una Base de Datos Bien Estructurada</h2><p>La normalizacion es el proceso de organizar una base de datos para reducir la redundancia. Las tres formas normales (1FN, 2FN, 3FN) son el estandar de la industria.</p>','','none',30,2,0),
(14,'Instalacion y Primeros Pasos con MySQL','<h2>Configurando MySQL en tu Sistema</h2><p>MySQL es el sistema de base de datos mas popular del mundo. Aprenderemos a instalarlo, configurar usuario root y crear nuestra primera base de datos.</p>','','none',15,3,0),
(15,'SELECT: Consultando Datos','<h2>La Instruccion mas Importante de SQL</h2><pre><code>-- Seleccionar todo\nSELECT * FROM usuarios;\n\n-- Seleccionar columnas especificas\nSELECT nombre, email FROM usuarios;\n\n-- Con condicion\nSELECT * FROM usuarios WHERE status = "activo";\n\n-- Ordenar resultados\nSELECT * FROM cursos ORDER BY precio DESC;\n\n-- Limitar resultados\nSELECT * FROM cursos LIMIT 10;</code></pre>','','none',25,1,0),
(15,'INSERT, UPDATE y DELETE','<h2>Modificando Datos en SQL</h2><pre><code>-- Insertar\nINSERT INTO usuarios (nombre, email) VALUES ("Ana", "ana@mail.com");\n\n-- Actualizar\nUPDATE usuarios SET status = "activo" WHERE id = 5;\n\n-- Eliminar\nDELETE FROM usuarios WHERE id = 5;\n\n-- Insertar multiples filas\nINSERT INTO cursos (titulo, nivel) VALUES\n("Python", "Basico"),\n("ML", "Avanzado");</code></pre>','','none',22,2,0),
(15,'WHERE, GROUP BY y HAVING','<h2>Filtrando y Agrupando Datos</h2><pre><code>-- Filtros complejos\nSELECT * FROM cursos WHERE nivel = "Avanzado" AND precio < 100;\n\n-- Agrupar y contar\nSELECT categoria, COUNT(*) as total FROM cursos GROUP BY categoria;\n\n-- Filtrar grupos\nSELECT categoria, COUNT(*) as total FROM cursos\nGROUP BY categoria HAVING total > 5;\n\n-- LIKE para patrones de texto\nSELECT * FROM usuarios WHERE nombre LIKE "%ana%";</code></pre>','','none',28,3,0),
(16,'INNER JOIN y LEFT JOIN','<h2>Combinando Datos de Multiples Tablas</h2><pre><code>-- INNER JOIN: solo registros que coinciden en ambas tablas\nSELECT u.nombre, c.titulo\nFROM usuarios u\nINNER JOIN inscripciones i ON u.id = i.user_id\nINNER JOIN cursos c ON i.course_id = c.id;\n\n-- LEFT JOIN: todos los registros de la tabla izquierda\nSELECT u.nombre, COUNT(i.id) as cursos_inscritos\nFROM usuarios u\nLEFT JOIN inscripciones i ON u.id = i.user_id\nGROUP BY u.id;</code></pre>','https://www.youtube.com/embed/9yeOJ0ZMUYw','youtube',35,1,0),
(16,'Subconsultas y Vistas','<h2>Consultas Dentro de Consultas</h2><pre><code>-- Subconsulta en WHERE\nSELECT * FROM cursos\nWHERE id IN (SELECT course_id FROM inscripciones WHERE user_id = 1);\n\n-- Crear una vista\nCREATE VIEW cursos_populares AS\nSELECT c.titulo, COUNT(i.id) as inscripciones\nFROM cursos c\nJOIN inscripciones i ON c.id = i.course_id\nGROUP BY c.id\nORDER BY inscripciones DESC;</code></pre>','','none',30,2,0),
(16,'Funciones de Agregacion','<h2>Calculando Estadisticas con SQL</h2><pre><code>-- Funciones basicas\nSELECT COUNT(*) as total FROM usuarios;\nSELECT AVG(calificacion) as promedio FROM resenas;\nSELECT MAX(precio) as mas_caro FROM cursos;\nSELECT MIN(precio) as mas_barato FROM cursos;\nSELECT SUM(ingresos) as total_ingresos FROM ventas;\n\n-- Con GROUP BY\nSELECT nivel, AVG(duracion_horas) as duracion_promedio\nFROM cursos GROUP BY nivel;</code></pre>','','none',22,3,0),
(17,'Indices y Rendimiento','<h2>Optimizando Consultas SQL</h2><p>Los indices son estructuras de datos que aceleran las consultas a cambio de algo de espacio en disco.</p><pre><code>-- Crear indice\nCREATE INDEX idx_email ON usuarios(email);\nCREATE INDEX idx_curso_nivel ON cursos(nivel, categoria);\n\n-- Analizar el plan de ejecucion\nEXPLAIN SELECT * FROM cursos WHERE nivel = "Avanzado";</code></pre>','','none',28,1,0),
(17,'Transacciones y ACID','<h2>Operaciones Atomicas en Bases de Datos</h2><p>Una transaccion es un conjunto de operaciones que se ejecutan como una unidad: o todas tienen exito, o ninguna se aplica.</p><pre><code>START TRANSACTION;\n\nINSERT INTO pedidos (user_id, total) VALUES (1, 150.00);\nUPDATE inventario SET stock = stock - 1 WHERE producto_id = 5;\n\nCOMMIT; -- Todo bien, confirmar\n-- ROLLBACK; -- Algo fallo, revertir todo</code></pre>','','none',25,2,0),
(17,'Procedimientos Almacenados','<h2>Logica de Negocio en la Base de Datos</h2><pre><code>DELIMITER //\nCREATE PROCEDURE obtener_cursos_por_nivel(IN nivel_param VARCHAR(50))\nBEGIN\n    SELECT id, titulo, duracion_horas, category\n    FROM cursos\n    WHERE nivel = nivel_param\n    ORDER BY titulo;\nEND //\nDELIMITER ;\n\n-- Ejecutar\nCALL obtener_cursos_por_nivel("Avanzado");</code></pre>','','none',30,3,0);

-- WEB FULL STACK LECCIONES (modules 18-22)
INSERT INTO `lessons` (`module_id`,`title`,`content`,`video_url`,`video_type`,`duration_minutes`,`sort_order`,`is_free`) VALUES
(18,'HTML5 Semantico','<h2>Estructura Correcta de un Documento HTML5</h2><p>HTML5 introdujo elementos semanticos que dan significado al contenido, mejorando accesibilidad y SEO.</p><pre><code>&lt;!DOCTYPE html&gt;\n&lt;html lang="es"&gt;\n&lt;head&gt;\n    &lt;meta charset="UTF-8"&gt;\n    &lt;title&gt;Mi Pagina&lt;/title&gt;\n&lt;/head&gt;\n&lt;body&gt;\n    &lt;header&gt;Cabecera&lt;/header&gt;\n    &lt;nav&gt;Navegacion&lt;/nav&gt;\n    &lt;main&gt;\n        &lt;article&gt;Contenido principal&lt;/article&gt;\n        &lt;aside&gt;Barra lateral&lt;/aside&gt;\n    &lt;/main&gt;\n    &lt;footer&gt;Pie de pagina&lt;/footer&gt;\n&lt;/body&gt;\n&lt;/html&gt;</code></pre>','https://www.youtube.com/embed/pQN-pnXPaVg','youtube',25,1,1),
(18,'CSS Grid y Flexbox','<h2>Layouts Modernos con CSS</h2><p>Flexbox es perfecto para layouts de una dimension, Grid para dos dimensiones.</p><pre><code>/* Flexbox */\n.contenedor {\n    display: flex;\n    justify-content: space-between;\n    align-items: center;\n    gap: 1rem;\n}\n\n/* Grid */\n.grid {\n    display: grid;\n    grid-template-columns: repeat(3, 1fr);\n    gap: 2rem;\n}</code></pre>','','none',35,2,0),
(18,'Animaciones y Transiciones CSS','<h2>Dando Vida a tus Interfaces</h2><p>Las animaciones CSS permiten crear experiencias fluidas sin JavaScript.</p><pre><code>/* Transicion suave */\n.boton {\n    transition: all 0.3s ease;\n}\n.boton:hover {\n    transform: translateY(-3px);\n    box-shadow: 0 10px 20px rgba(0,0,0,0.2);\n}\n\n/* Animacion */\n@keyframes fadeIn {\n    from { opacity: 0; transform: translateY(20px); }\n    to { opacity: 1; transform: translateY(0); }\n}</code></pre>','','none',30,3,0),
(19,'DOM: Manipulacion de la Pagina','<h2>JavaScript y el Document Object Model</h2><pre><code>// Seleccionar elementos\nconst titulo = document.querySelector("h1");\nconst botones = document.querySelectorAll(".boton");\n\n// Modificar contenido\ntitulo.textContent = "Nuevo titulo";\ntitulo.style.color = "#38bdf8";\n\n// Crear y agregar elementos\nconst nuevoParrafo = document.createElement("p");\nnuevoParrafo.textContent = "Texto dinamico";\ndocument.body.appendChild(nuevoParrafo);</code></pre>','','none',30,1,0),
(19,'Eventos en JavaScript','<h2>Responder a Acciones del Usuario</h2><pre><code>// Click\nboton.addEventListener("click", function() {\n    alert("Boton clickeado!");\n});\n\n// Formularios\nform.addEventListener("submit", function(e) {\n    e.preventDefault(); // Evitar recarga\n    const datos = new FormData(e.target);\n    console.log(Object.fromEntries(datos));\n});\n\n// Teclas\ndocument.addEventListener("keydown", (e) => {\n    if (e.key === "Escape") cerrarModal();\n});</code></pre>','','none',25,2,0),
(19,'Fetch API y AJAX','<h2>Comunicacion Asincrona con el Servidor</h2><pre><code>// Fetch GET\nfetch("https://api.ejemplo.com/cursos")\n    .then(res => res.json())\n    .then(data => console.log(data))\n    .catch(err => console.error(err));\n\n// Fetch con async/await\nasync function obtenerCursos() {\n    try {\n        const res = await fetch("/api/cursos");\n        const cursos = await res.json();\n        return cursos;\n    } catch (error) {\n        console.error("Error:", error);\n    }\n}</code></pre>','','none',28,3,0),
(20,'PHP 8: Sintaxis Moderna','<h2>PHP 8 Moderno y Profesional</h2><p>PHP 8 introdujo muchas mejoras que lo hacen un lenguaje moderno y eficiente.</p><pre><code>&lt;?php\n// Named arguments\narray_slice(array: $arr, offset: 2, length: 3);\n\n// Match expression (mejor que switch)\n$estado = "activo";\n$texto = match($estado) {\n    "activo" => "Verde",\n    "inactivo" => "Rojo",\n    default => "Gris"\n};\n\n// Nullsafe operator\n$ciudad = $usuario?->getDireccion()?->getCiudad();</code></pre>','','none',30,1,0),
(20,'Arquitectura MVC con PHP','<h2>Separacion de Responsabilidades</h2><p>MVC divide la aplicacion en tres capas: Modelo (datos), Vista (presentacion) y Controlador (logica).</p>','','none',35,2,0),
(20,'Seguridad en PHP: SQL Injection y XSS','<h2>Protegiendo tu Aplicacion</h2><p>La seguridad es obligatoria. Las dos vulnerabilidades mas comunes son SQL Injection y Cross-Site Scripting (XSS).</p><pre><code>&lt;?php\n// NUNCA hagas esto (vulnerable a SQL Injection)\n$query = "SELECT * FROM users WHERE id = " . $_GET["id"];\n\n// SIEMPRE usa prepared statements\n$stmt = $pdo->prepare("SELECT * FROM users WHERE id = ?");\n$stmt->execute([$_GET["id"]]);\n\n// Sanitizar salida HTML (prevenir XSS)\necho htmlspecialchars($usuario["nombre"], ENT_QUOTES, "UTF-8");</code></pre>','','none',30,3,0),
(21,'PDO y Consultas Preparadas','<h2>Acceso Seguro a la Base de Datos con PDO</h2><pre><code>&lt;?php\n$pdo = new PDO("mysql:host=localhost;dbname=midb;charset=utf8mb4", "user", "pass");\n$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);\n\n// Consulta preparada\n$stmt = $pdo->prepare("SELECT * FROM cursos WHERE nivel = :nivel");\n$stmt->execute(["nivel" => "Avanzado"]);\n$cursos = $stmt->fetchAll(PDO::FETCH_ASSOC);</code></pre>','','none',25,1,0),
(21,'Relaciones en Base de Datos con PHP','<h2>JOINs y Relaciones en PHP/MySQL</h2><p>Consultas con relaciones entre tablas usando PDO y como mapear los resultados a estructuras PHP.</p>','','none',30,2,0),
(21,'API REST con PHP','<h2>Construyendo una API RESTful</h2><p>Una API REST permite que tu frontend se comunique con el backend de forma estandarizada.</p><pre><code>&lt;?php\nheader("Content-Type: application/json; charset=utf-8");\nheader("Access-Control-Allow-Origin: *");\n\n$method = $_SERVER["REQUEST_METHOD"];\n\nif ($method === "GET") {\n    $cursos = $db->query("SELECT * FROM cursos")->fetchAll();\n    echo json_encode(["success" => true, "data" => $cursos]);\n}</code></pre>','','none',35,3,0),
(22,'Integrando Frontend y Backend','<h2>Conectando todas las Piezas</h2><p>El proyecto final integra HTML, CSS, JavaScript, PHP y MySQL en una aplicacion web completa y funcional.</p>','https://www.youtube.com/embed/ysEN5RaKOlA','youtube',45,1,0),
(22,'Subida de Archivos e Imagenes','<h2>Manejo Seguro de Archivos en PHP</h2><pre><code>&lt;?php\nif ($_FILES["imagen"]["error"] === 0) {\n    $extension = pathinfo($_FILES["imagen"]["name"], PATHINFO_EXTENSION);\n    $extensiones_permitidas = ["jpg", "png", "gif", "webp"];\n    \n    if (in_array(strtolower($extension), $extensiones_permitidas)) {\n        $nombre = uniqid() . "." . $extension;\n        move_uploaded_file($_FILES["imagen"]["tmp_name"], "uploads/" . $nombre);\n    }\n}</code></pre>','','none',30,2,0),
(22,'Despliegue en Hosting Real','<h2>Llevando tu App a Produccion</h2><p>Aprenderemos a desplegar la aplicacion en un hosting real: configurar el servidor, subir archivos por FTP, configurar la base de datos y el dominio.</p>','','none',35,3,0);

-- ALGORITMOS GENETICOS LECCIONES (modules 23-26)
INSERT INTO `lessons` (`module_id`,`title`,`content`,`video_url`,`video_type`,`duration_minutes`,`sort_order`,`is_free`) VALUES
(23,'Darwin y la Computacion','<h2>La Seleccion Natural como Algoritmo</h2><p>Charles Darwin observo que los organismos mas adaptados a su entorno tienen mas probabilidades de sobrevivir y reproducirse, pasando sus caracteristicas a la siguiente generacion. Los algoritmos geneticos simulan exactamente este proceso para resolver problemas de optimizacion.</p>','https://www.youtube.com/embed/1i8muvzZkPw','youtube',20,1,1),
(23,'Problemas de Optimizacion','<h2>Que Problemas Resuelven los AG?</h2><p>Los algoritmos geneticos son especialmente utiles para problemas donde el espacio de busqueda es enorme y no se puede explorar exhaustivamente.</p><ul><li>Problema del Viajante (TSP)</li><li>Optimizacion de portafolios financieros</li><li>Scheduling y planificacion</li><li>Diseño de redes neuronales (NeuroEvolution)</li><li>Generacion de arte y musica</li></ul>','','none',18,2,0),
(23,'Comparacion con otros Metodos','<h2>AG vs Metodos Tradicionales</h2><p>Los AG no siempre son la mejor opcion. Comparamos con hill climbing, simulated annealing y busqueda exhaustiva para entender cuando usar cada uno.</p>','','none',15,3,0),
(24,'Cromosomas y Codificacion','<h2>Representando Soluciones como Cromosomas</h2><p>En un AG, cada posible solucion al problema se representa como un "cromosoma", tipicamente una cadena de bits, numeros o caracteres.</p><pre><code># Ejemplo: ruta de 5 ciudades como cromosoma\ncromosoma = [2, 4, 1, 3, 5]  # orden de visita\n\n# Poblacion inicial aleatoria\nimport random\ndef crear_poblacion(tam_poblacion, num_ciudades):\n    return [random.sample(range(num_ciudades), num_ciudades)\n            for _ in range(tam_poblacion)]</code></pre>','','none',25,1,0),
(24,'Funcion de Aptitud (Fitness)','<h2>Evaluando la Calidad de Soluciones</h2><p>La funcion de aptitud determina que tan "buena" es una solucion. Es el equivalente al entorno en la seleccion natural.</p><pre><code>def calcular_distancia(ruta, distancias):\n    total = 0\n    for i in range(len(ruta) - 1):\n        total += distancias[ruta[i]][ruta[i+1]]\n    total += distancias[ruta[-1]][ruta[0]]  # regresar al inicio\n    return total\n\n# Fitness: menor distancia = mejor aptitud\ndef fitness(cromosoma, distancias):\n    return 1 / calcular_distancia(cromosoma, distancias)</code></pre>','','none',28,2,0),
(24,'Seleccion de Padres','<h2>Eligiendo los Mejores para Reproducirse</h2><p>Existen varios metodos de seleccion. El torneo es simple y efectivo: seleccionar k individuos aleatoriamente y elegir el mejor.</p><pre><code>def seleccion_por_torneo(poblacion, fitnesses, k=3):\n    participantes = random.sample(list(enumerate(poblacion)), k)\n    ganador = max(participantes, key=lambda x: fitnesses[x[0]])\n    return ganador[1]</code></pre>','','none',22,3,0),
(25,'Cruce (Crossover)','<h2>Combinando Soluciones Parentales</h2><pre><code>def cruce_un_punto(padre1, padre2):\n    n = len(padre1)\n    punto = random.randint(1, n-1)\n    hijo1 = padre1[:punto] + padre2[punto:]\n    hijo2 = padre2[:punto] + padre1[punto:]\n    return hijo1, hijo2\n\ndef cruce_orden(padre1, padre2):\n    """Para permutaciones (ej: TSP)"""\n    n = len(padre1)\n    inicio, fin = sorted(random.sample(range(n), 2))\n    hijo = [-1] * n\n    hijo[inicio:fin] = padre1[inicio:fin]\n    restantes = [x for x in padre2 if x not in hijo]\n    j = 0\n    for i in range(n):\n        if hijo[i] == -1:\n            hijo[i] = restantes[j]\n            j += 1\n    return hijo</code></pre>','','none',30,1,0),
(25,'Mutacion','<h2>Introduciendo Variabilidad Genetica</h2><pre><code>def mutacion_intercambio(cromosoma, tasa=0.01):\n    """Intercambia dos genes aleatoriamente"""\n    if random.random() < tasa:\n        i, j = random.sample(range(len(cromosoma)), 2)\n        cromosoma[i], cromosoma[j] = cromosoma[j], cromosoma[i]\n    return cromosoma\n\ndef mutacion_inversion(cromosoma, tasa=0.01):\n    """Invierte un segmento aleatorio"""\n    if random.random() < tasa:\n        i, j = sorted(random.sample(range(len(cromosoma)), 2))\n        cromosoma[i:j] = reversed(cromosoma[i:j])\n    return cromosoma</code></pre>','','none',25,2,0),
(25,'Convergencia y Parametros','<h2>Ajustando los Parametros del AG</h2><p>Los parametros clave son: tamano de poblacion, tasa de cruce, tasa de mutacion y criterio de parada. El ajuste fino de estos parametros es crucial para el exito del algoritmo.</p>','','none',20,3,0),
(26,'Proyecto: Resolver el TSP','<h2>Problema del Viajante con Algoritmo Genetico</h2><p>Implementaremos un AG completo para resolver el Problema del Viajante (Traveling Salesman Problem), uno de los problemas de optimizacion mas famosos en ciencias de la computacion.</p>','https://www.youtube.com/embed/9zfeTw-uFCw','youtube',45,1,0),
(26,'Proyecto: Optimizacion de Funciones','<h2>Encontrar el Maximo Global de una Funcion</h2><p>Usaremos AG para encontrar el maximo de una funcion matematica compleja con multiples maximos locales, donde los metodos de gradiente fallarian.</p>','','none',35,2,0),
(26,'Extensiones: NSGA-II y AG Multi-Objetivo','<h2>Optimizacion con Multiples Objetivos</h2><p>En problemas reales, frecuentemente hay que optimizar multiples objetivos contradictorios simultaneamente. NSGA-II es el estandar para optimizacion multi-objetivo evolutiva.</p>','','none',30,3,0);

-- DATA SCIENCE LECCIONES (modules 27-30)
INSERT INTO `lessons` (`module_id`,`title`,`content`,`video_url`,`video_type`,`duration_minutes`,`sort_order`,`is_free`) VALUES
(27,'Que hace un Data Scientist','<h2>El Rol del Cientifico de Datos</h2><p>Un Data Scientist combina estadistica, programacion y conocimiento de dominio para extraer insights valiosos de los datos. Es uno de los roles mejor pagados y mas demandados del mercado tecnologico.</p>','https://www.youtube.com/embed/xC-c7E5PK0Y','youtube',20,1,1),
(27,'CRISP-DM: El Proceso Estandar','<h2>Cross-Industry Standard Process for Data Mining</h2><p>CRISP-DM define 6 fases iterativas: Comprension del negocio, Comprension de los datos, Preparacion de datos, Modelado, Evaluacion y Despliegue.</p>','','none',25,2,0),
(27,'Jupyter Notebooks y Herramientas','<h2>Configurando tu Entorno de Data Science</h2><p>Jupyter Notebook es el estandar para experimentacion en Data Science. Permite combinar codigo, visualizaciones y texto en un solo documento interactivo.</p>','','none',20,3,0),
(28,'Web Scraping con Beautiful Soup','<h2>Extrayendo Datos de la Web</h2><pre><code>import requests\nfrom bs4 import BeautifulSoup\n\nurl = "https://quotes.toscrape.com"\nresponse = requests.get(url)\nsoup = BeautifulSoup(response.text, "html.parser")\n\nquotes = soup.find_all("div", class_="quote")\nfor q in quotes:\n    texto = q.find("span", class_="text").text\n    autor = q.find("small", class_="author").text\n    print(f"{texto} - {autor}")</code></pre>','','none',30,1,0),
(28,'pandas: El Lenguaje de los Datos','<h2>Manipulacion de Datos con pandas</h2><pre><code>import pandas as pd\n\n# Cargar datos\ndf = pd.read_csv("datos.csv")\n\n# Explorar\nprint(df.head())\nprint(df.describe())\nprint(df.info())\n\n# Limpiar\ndf.dropna(inplace=True)\ndf = df[df["precio"] > 0]\n\n# Transformar\ndf["precio_USD"] = df["precio_COP"] / 4000\n\n# Agrupar\nresumen = df.groupby("categoria")["precio"].mean()</code></pre>','https://www.youtube.com/embed/vmEHCJofslg','youtube',40,2,0),
(28,'Limpieza y Preprocesamiento de Datos','<h2>Datos Limpios = Modelos Mejores</h2><p>El 80% del tiempo en Data Science se gasta en limpieza de datos. Aprenderemos a detectar y tratar valores nulos, outliers, datos duplicados y formatos incorrectos.</p>','','none',35,3,0),
(29,'Estadisticas Descriptivas con pandas','<h2>Describiendo los Datos</h2><pre><code>import pandas as pd\nimport numpy as np\n\n# Medidas de tendencia central\nprint(df["precio"].mean())   # Media\nprint(df["precio"].median()) # Mediana\nprint(df["precio"].mode())   # Moda\n\n# Medidas de dispersion\nprint(df["precio"].std())    # Desviacion estandar\nprint(df["precio"].var())    # Varianza\nprint(df["precio"].quantile([0.25, 0.5, 0.75]))</code></pre>','','none',28,1,0),
(29,'Correlaciones y Relaciones','<h2>Encontrando Relaciones entre Variables</h2><p>La correlacion mide la relacion lineal entre dos variables. Es fundamental para entender que factores influyen en el fenomeno que estamos estudiando.</p><pre><code># Matriz de correlacion\ncorr_matrix = df.corr()\n\n# Visualizar con seaborn\nimport seaborn as sns\nsns.heatmap(corr_matrix, annot=True, cmap="coolwarm")</code></pre>','','none',30,2,0),
(29,'Distribuciones de Probabilidad','<h2>Entendiendo como se Distribuyen los Datos</h2><p>Las distribuciones de probabilidad describen como se comportan los datos. La normal, la Poisson, la exponencial y otras son fundamentales para el modelado estadistico.</p>','','none',25,3,0),
(30,'Visualizacion con matplotlib y seaborn','<h2>Comunicando con Graficas Profesionales</h2><pre><code>import matplotlib.pyplot as plt\nimport seaborn as sns\n\n# Configuracion de estilo\nplt.style.use("dark_background")\n\n# Histograma\nplt.figure(figsize=(10, 6))\nsns.histplot(df["precio"], bins=30, kde=True)\nplt.title("Distribucion de Precios")\nplt.xlabel("Precio")\nplt.show()\n\n# Scatterplot con regresion\nsns.regplot(x="area", y="precio", data=df)</code></pre>','https://www.youtube.com/embed/a9UrKTVEeZA','youtube',35,1,0),
(30,'Plotly: Visualizaciones Interactivas','<h2>Dashboards Interactivos con Plotly</h2><p>Plotly permite crear graficas interactivas que los usuarios pueden explorar, filtrar y hacer zoom. Es ideal para presentaciones y reportes ejecutivos.</p>','','none',30,2,0),
(30,'Storytelling con Datos','<h2>Comunicando tus Hallazgos Efectivamente</h2><p>Un Data Scientist no solo analiza datos; tambien debe comunicar sus hallazgos de forma clara y convincente. Aprenderemos principios de diseno visual y narracion de datos.</p>','','none',25,3,0);

-- JAVASCRIPT MODERNO LECCIONES (modules 31-35)
INSERT INTO `lessons` (`module_id`,`title`,`content`,`video_url`,`video_type`,`duration_minutes`,`sort_order`,`is_free`) VALUES
(31,'Introduccion a JavaScript','<h2>El Lenguaje de la Web</h2><p>JavaScript es el unico lenguaje de programacion que se ejecuta nativamente en los navegadores. Fue creado en 10 dias por Brendan Eich en 1995 y hoy es el lenguaje mas usado del mundo.</p>','https://www.youtube.com/embed/RqQ1d1qEWlE','youtube',18,1,1),
(31,'Variables: var, let y const','<h2>Declarando Variables en JavaScript Moderno</h2><pre><code>// var - alcance de funcion, izar (hoisting)\nvar nombre = "Juan";\n\n// let - alcance de bloque, reasignable\nlet edad = 25;\nedad = 26; // OK\n\n// const - alcance de bloque, no reasignable\nconst PI = 3.14159;\n// PI = 3; // ERROR\n\n// const con objetos (el objeto si puede mutar)\nconst persona = { nombre: "Ana" };\npersona.nombre = "Maria"; // OK</code></pre>','','none',22,2,0),
(31,'Funciones y Closures','<h2>Funciones en JavaScript</h2><pre><code>// Funcion tradicional\nfunction sumar(a, b) { return a + b; }\n\n// Arrow function\nconst multiplicar = (a, b) => a * b;\n\n// Closure: funcion que recuerda su entorno\nfunction crearContador() {\n    let cuenta = 0;\n    return function() {\n        cuenta++;\n        return cuenta;\n    };\n}\nconst contador = crearContador();\nconsole.log(contador()); // 1\nconsole.log(contador()); // 2</code></pre>','','none',28,3,0),
(32,'Arrow Functions y This','<h2>El Contexto this en JavaScript</h2><p>El comportamiento de "this" es uno de los temas mas confusos de JavaScript. Las arrow functions resuelven muchos problemas de contexto.</p><pre><code>// this en metodo de objeto\nconst objeto = {\n    nombre: "Mi Objeto",\n    saludar: function() {\n        return `Hola desde ${this.nombre}`;\n    }\n};\n\n// Arrow function NO tiene su propio this\nconst objeto2 = {\n    nombre: "Mi Objeto",\n    saludar: () => `Hola desde ${this.nombre}` // undefined!\n};</code></pre>','','none',25,1,0),
(32,'Destructuring y Spread Operator','<h2>Sintaxis Moderna de ES6+</h2><pre><code>// Destructuring de objetos\nconst { nombre, edad, ciudad = "Bogota" } = persona;\n\n// Destructuring de arrays\nconst [primero, segundo, ...resto] = [1, 2, 3, 4, 5];\n\n// Spread operator\nconst arr1 = [1, 2, 3];\nconst arr2 = [4, 5, 6];\nconst combinado = [...arr1, ...arr2];\n\n// Copiar objetos\nconst copia = { ...original, nombre: "Nuevo" };</code></pre>','','none',28,2,0),
(32,'Modulos ES6: import y export','<h2>Organizando el Codigo en Modulos</h2><pre><code>// matematicas.js\nexport const PI = 3.14159;\nexport function area(radio) {\n    return PI * radio ** 2;\n}\nexport default function circunferencia(radio) {\n    return 2 * PI * radio;\n}\n\n// main.js\nimport circunferencia, { PI, area } from "./matematicas.js";\nconsole.log(area(5));           // 78.54\nconsole.log(circunferencia(5)); // 31.42</code></pre>','','none',22,3,0),
(33,'Event Loop y Asincronismo','<h2>Como JavaScript Maneja el Tiempo</h2><p>JavaScript es single-threaded pero puede manejar operaciones asincronas gracias al Event Loop. Entender esto es fundamental para escribir codigo asincrono correcto.</p>','https://www.youtube.com/embed/8aGhZQkoFbQ','youtube',30,1,0),
(33,'Promises: Encadenando lo Asincrono','<h2>Manejo de Operaciones Asincronas</h2><pre><code>// Crear una Promise\nconst promise = new Promise((resolve, reject) => {\n    setTimeout(() => {\n        resolve("Exito!");\n        // reject(new Error("Fallo"));\n    }, 2000);\n});\n\n// Consumir con .then().catch()\npromise\n    .then(resultado => console.log(resultado))\n    .catch(error => console.error(error))\n    .finally(() => console.log("Finalizado"));\n\n// Promise.all para multiples promesas paralelas\nPromise.all([fetch(url1), fetch(url2), fetch(url3)])\n    .then(respuestas => { /* todas completadas */ });</code></pre>','','none',30,2,0),
(33,'async/await: La Forma Moderna','<h2>Codigo Asincrono que Parece Sincrono</h2><pre><code>async function obtenerDatos(url) {\n    try {\n        const respuesta = await fetch(url);\n        \n        if (!respuesta.ok) {\n            throw new Error(`HTTP ${respuesta.status}`);\n        }\n        \n        const datos = await respuesta.json();\n        return datos;\n    } catch (error) {\n        console.error("Error al obtener datos:", error);\n        throw error;\n    }\n}\n\n// Llamada\nobtenerDatos("/api/cursos")\n    .then(cursos => console.log(cursos))\n    .catch(e => console.error(e));</code></pre>','','none',28,3,0),
(34,'Que es React y JSX','<h2>Introduccion a React</h2><p>React es una libreria de JavaScript para construir interfaces de usuario. Fue creada por Facebook (Meta) en 2013 y se ha convertido en la opcion mas popular para el desarrollo frontend.</p>','https://www.youtube.com/embed/Tn6-PIqc4UM','youtube',25,1,0),
(34,'Componentes y Props','<h2>Los Bloques de Construccion de React</h2><pre><code>// Componente funcional\nfunction TarjetaCurso({ titulo, nivel, imagen, duracion }) {\n    return (\n        &lt;div className="card"&gt;\n            &lt;img src={imagen} alt={titulo} /&gt;\n            &lt;h3&gt;{titulo}&lt;/h3&gt;\n            &lt;span&gt;{nivel}&lt;/span&gt;\n            &lt;p&gt;{duracion} horas&lt;/p&gt;\n        &lt;/div&gt;\n    );\n}\n\n// Uso\n&lt;TarjetaCurso \n    titulo="Python desde Cero"\n    nivel="Basico"\n    imagen="/python.jpg"\n    duracion={35}\n/&gt;</code></pre>','','none',30,2,0),
(34,'useState y useEffect','<h2>Hooks Fundamentales de React</h2><pre><code>import { useState, useEffect } from "react";\n\nfunction Contador() {\n    const [cuenta, setCuenta] = useState(0);\n    \n    // Efecto al montar el componente\n    useEffect(() => {\n        document.title = `Contador: ${cuenta}`;\n    }, [cuenta]); // Ejecutar cuando cambie "cuenta"\n    \n    return (\n        &lt;div&gt;\n            &lt;p&gt;Cuenta: {cuenta}&lt;/p&gt;\n            &lt;button onClick={() => setCuenta(c => c + 1)}&gt;\n                Incrementar\n            &lt;/button&gt;\n        &lt;/div&gt;\n    );\n}</code></pre>','','none',35,3,0),
(35,'Proyecto React: Catalogo de Cursos','<h2>Construyendo un Catalogo de Cursos con React</h2><p>Crearemos una SPA (Single Page Application) que consume una API REST y muestra un catalogo de cursos con busqueda, filtros y carrito de compras. Este proyecto integra todos los conceptos aprendidos.</p>','https://www.youtube.com/embed/w7ejDZ8SWv8','youtube',50,1,0),
(35,'Estado Global con Context API','<h2>Compartiendo Estado entre Componentes</h2><p>A medida que la app crece, necesitamos compartir estado entre componentes distantes. Context API es la solucion nativa de React.</p>','','none',35,2,0),
(35,'Despliegue de App React en Vercel','<h2>Tu App React en Internet en 5 Minutos</h2><p>Vercel es la plataforma ideal para desplegar aplicaciones React. Conectas tu repositorio de GitHub y cada push automaticamente despliega una nueva version.</p>','','none',20,3,0);

SET FOREIGN_KEY_CHECKS = 1;

SELECT CONCAT('SEED COMPLETADO: ', 
  (SELECT COUNT(*) FROM courses), ' cursos, ',
  (SELECT COUNT(*) FROM modules), ' modulos, ',
  (SELECT COUNT(*) FROM lessons), ' lecciones insertadas.') AS resultado;
